"""
fvei_dataloader.py

PyTorch Dataset and DataLoader implementation for the FVEI
real-world visibility estimation dataset.

The dataset is read directly from the original ZIP archive.
Split membership is defined by the reproducible final FVEI
split manifest generated by src.data.split_fvei.

Author: Ilayda Ozturk
Project: TUBITAK 2209-A
"""

import argparse
import csv
import io
import zipfile
from pathlib import Path
from typing import Optional

import torch
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms

from src.training.config import (
    BATCH_SIZE,
    IMAGE_SIZE,
    NUM_WORKERS,
    RANDOM_SEED,
)
from src.training.dataloader import get_transforms


ROOT = Path(__file__).resolve().parents[2]

DEFAULT_MANIFEST = (
    ROOT
    / "data"
    / "processed"
    / "fvei"
    / "fvei_final_split_manifest.csv"
)


class FVEIDataset(Dataset):
    """
    Dataset for FVEI images stored inside the original ZIP archive.

    Exact-label splits:
        train
        val
        test

    Separate analysis split:
        ceiling_eval
    """

    def __init__(
        self,
        zip_path: Path,
        manifest_path: Path,
        split: str,
        transform: Optional[transforms.Compose] = None,
    ) -> None:
        self.zip_path = Path(zip_path)
        self.manifest_path = Path(manifest_path)
        self.split = split
        self.transform = transform

        if not self.zip_path.exists():
            raise FileNotFoundError(
                f"FVEI ZIP not found: {self.zip_path}"
            )

        if not self.manifest_path.exists():
            raise FileNotFoundError(
                f"FVEI split manifest not found: "
                f"{self.manifest_path}"
            )

        allowed_splits = {
            "train",
            "val",
            "test",
            "ceiling_eval",
        }

        if split not in allowed_splits:
            raise ValueError(
                f"Unsupported split: {split}. "
                f"Expected one of {sorted(allowed_splits)}."
            )

        with self.manifest_path.open(
            encoding="utf-8-sig",
            newline="",
        ) as handle:
            rows = list(csv.DictReader(handle))

        required_columns = {
            "zip_member",
            "level",
            "visibility_m",
            "label_kind",
            "sha256",
            "split",
        }

        if not rows:
            raise ValueError(
                "FVEI split manifest is empty."
            )

        missing_columns = (
            required_columns - set(rows[0].keys())
        )

        if missing_columns:
            raise ValueError(
                "Missing FVEI manifest columns: "
                f"{sorted(missing_columns)}"
            )

        self.rows = [
            row
            for row in rows
            if row["split"] == split
        ]

        if not self.rows:
            raise ValueError(
                f"No samples found for split: {split}"
            )

        if split in {"train", "val", "test"}:
            invalid = [
                row["zip_member"]
                for row in self.rows
                if row["label_kind"] != "exact"
            ]

            if invalid:
                raise ValueError(
                    "Exact-label split contains "
                    "non-exact labels."
                )

        if split == "ceiling_eval":
            invalid = [
                row["zip_member"]
                for row in self.rows
                if row["label_kind"] != "ceiling"
            ]

            if invalid:
                raise ValueError(
                    "ceiling_eval contains "
                    "non-ceiling labels."
                )

        self._archive = None

    def __len__(self) -> int:
        return len(self.rows)

    def _get_archive(self) -> zipfile.ZipFile:
        if self._archive is None:
            self._archive = zipfile.ZipFile(
                self.zip_path,
                mode="r",
            )

        return self._archive

    def __getitem__(
        self,
        index: int,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        row = self.rows[index]

        archive = self._get_archive()

        try:
            image_bytes = archive.read(
                row["zip_member"]
            )
        except KeyError as error:
            raise FileNotFoundError(
                "Image listed in manifest was not "
                f"found in ZIP: {row['zip_member']}"
            ) from error

        with Image.open(
            io.BytesIO(image_bytes)
        ) as image_file:
            image = image_file.convert("RGB")

        if self.transform is not None:
            image = self.transform(image)

        visibility = torch.tensor(
            float(row["visibility_m"]),
            dtype=torch.float32,
        )

        return image, visibility

    def __del__(self) -> None:
        archive = getattr(
            self,
            "_archive",
            None,
        )

        if archive is not None:
            try:
                archive.close()
            except Exception:
                pass


def create_fvei_dataloaders(
    zip_path: Path,
    manifest_path: Path = DEFAULT_MANIFEST,
    image_size: int = IMAGE_SIZE,
    batch_size: int = BATCH_SIZE,
    num_workers: int = NUM_WORKERS,
    random_seed: int = RANDOM_SEED,
    pin_memory: bool = False,
) -> tuple[
    DataLoader,
    DataLoader,
    DataLoader,
    DataLoader,
]:
    """
    Create FVEI train, validation, held-out test,
    and ceiling-evaluation DataLoaders.
    """

    transform = get_transforms(
        image_size=image_size,
    )

    train_dataset = FVEIDataset(
        zip_path=zip_path,
        manifest_path=manifest_path,
        split="train",
        transform=transform,
    )

    val_dataset = FVEIDataset(
        zip_path=zip_path,
        manifest_path=manifest_path,
        split="val",
        transform=transform,
    )

    test_dataset = FVEIDataset(
        zip_path=zip_path,
        manifest_path=manifest_path,
        split="test",
        transform=transform,
    )

    ceiling_dataset = FVEIDataset(
        zip_path=zip_path,
        manifest_path=manifest_path,
        split="ceiling_eval",
        transform=transform,
    )

    generator = torch.Generator()
    generator.manual_seed(random_seed)

    train_loader = DataLoader(
        dataset=train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=pin_memory,
        generator=generator,
    )

    val_loader = DataLoader(
        dataset=val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory,
    )

    test_loader = DataLoader(
        dataset=test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory,
    )

    ceiling_loader = DataLoader(
        dataset=ceiling_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory,
    )

    return (
        train_loader,
        val_loader,
        test_loader,
        ceiling_loader,
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Test the FVEI DataLoader."
    )

    parser.add_argument(
        "--zip-path",
        type=Path,
        required=True,
        help="Path to the original FVEI ZIP.",
    )

    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
    )

    args = parser.parse_args()

    (
        train_loader,
        val_loader,
        test_loader,
        ceiling_loader,
    ) = create_fvei_dataloaders(
        zip_path=args.zip_path,
        manifest_path=args.manifest,
    )

    print("=" * 60)
    print("FVEI DataLoader Test")
    print("=" * 60)

    print(
        f"Train images       : "
        f"{len(train_loader.dataset)}"
    )
    print(
        f"Validation images  : "
        f"{len(val_loader.dataset)}"
    )
    print(
        f"Held-out test      : "
        f"{len(test_loader.dataset)}"
    )
    print(
        f"Ceiling evaluation : "
        f"{len(ceiling_loader.dataset)}"
    )

    images, labels = next(
        iter(train_loader)
    )

    print(
        f"\nTrain batch shape  : "
        f"{images.shape}"
    )
    print(
        f"Label batch shape  : "
        f"{labels.shape}"
    )
    print(
        f"Batch label min    : "
        f"{labels.min().item():.2f} m"
    )
    print(
        f"Batch label max    : "
        f"{labels.max().item():.2f} m"
    )

    print(
        "\nFVEI DataLoaders created successfully."
    )


if __name__ == "__main__":
    main()
